version: '3'

services:
  server:
    build:
      context: ./site
    ports:
      - 3000:3000
    container_name: simpsocks_server
    command: npm run startdev 
    env_file: .env
    volumes:
      - ./site:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - db
  db:
    image: mysql:8.0
    container_name: simpsocks_db
    environment:
      - MYSQL_USER
      - MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE
    command: --character-set-server=utf8mb4
    restart: always
    volumes:
      - db:/var/lib/mysql
  dashboard:
    build:
      context: ./dashboard
    ports:
      - 3001:3000
    container_name: simpsocks_ui
    stdin_open: true
    volumes:
       - ./dashboard:/usr/src/app
       - /usr/src/app/node_modules
volumes:
  db: