version: '3'

services:
  server:
    build: .
    container_name: simpsocks_server
    command: npm start 
    ports:
      - 3000:3000
    env_file: .env.production
    volumes:
      - ./site:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - db
  db:
    image: mysql:8.0
    container_name: simpsocks_db
    env_file: .env.production
    command: --character-set-server=utf8mb4
    restart: always
    volumes:
      - db:/var/lib/mysql
volumes:
  db: